[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm install && npm run build:prod"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VUE_APP_API_BASE_URL = "https://your-backend-url.up.railway.app/api/transactions"

[context.production]
  environment = { VUE_APP_ENVIRONMENT = "production", VUE_APP_DEBUG = "false" }

[context.deploy-preview]
  command = "npm install && npm run build"
  environment = { VUE_APP_ENVIRONMENT = "staging" }
